WeatherStation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

app_name = 'api'
urlpatterns = [
    path('time', views.get_time, name='get_time'),
    path('token', obtain_auth_token, name='get_token'),
    path('check/token', views.check_token, name='check_token'),
    path('check/sensor_id', views.check_sensor_id, name='check_sensor_id'),
    path('user/', views.get_user, name='get_user'),
    path('sensors/', views.get_sensor, name='get_sensor'),
    path('sensors/<int:sensor_id>/', views.get_data, name='get_data'),
    path('sensors/add', views.add_data, name='add_data'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('', views.index, name='about'),  # future
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('sensor/<int:sensor_num>', views.sensor, name='sensor'),
    path('sensor/<int:sensor_num>/download', views.get_sensor_data, name='get_sensor_data'),
    path('sensor/<int:sensor_num>/delete', views.delete_sensor_data, name='delete_sensor_data'),
]

main/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
import pytz
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


class Sensor(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name='sensors', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class DataPoint(models.Model):
    class AirDirection(models.TextChoices):
        NORTH = 'N'
        NORTH_EAST = 'NE'
        EAST = 'E'
        SOUTH_EAST = 'SE'
        SOUTH = 'S'
        SOUTH_WEST = 'SW'
        WEST = 'W'
        NORTH_WEST = 'NW'

    date = models.DateTimeField("Date Collected", primary_key=True)
    temperature = models.FloatField("Temperature")
    humidity = models.FloatField("Humidity")
    pressure = models.FloatField("Pressure")
    air_speed = models.FloatField("Air Speed")
    air_direction = models.CharField(
        max_length=2,
        choices=AirDirection.choices,
    )
    sensor = models.ForeignKey(Sensor, related_name='datapoint', on_delete=models.CASCADE)

    def __str__(self):
        return self.date.astimezone(pytz.timezone("Asia/Dhaka")).strftime("%Y-%m-%d %H:%M:%S GMT%Z")


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

main/views.py
import csv

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import DataPoint, Sensor


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'main/login.html')
    sensors = Sensor.objects.filter(owner=request.user)
    context = {'sensors': sensors}
    return render(request, 'main/index.html', context)


def user_login(request):
    logout(request)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('main:index', args=None))
            # return render(request, 'main/login.html',)
        else:
            return render(request, 'main/login.html', {'failed_login': True})
    else:
        return render(request, 'main/login.html', )


def user_logout(request):
    logout(request)
    return render(request, 'main/login.html')


def sensor(request, sensor_num):
    if not request.user.is_authenticated:
        return render(request, 'main/login.html')
    try:
        sensors = Sensor.objects.filter(owner=request.user).get(id=sensor_num)
    except Sensor.DoesNotExist:
        raise Http404("Sensor does not exists")
    # datapoint = DataPoint.objects.filter(sensor=sensors).order_by('-date')[:100]
    context = {
        'sensors': sensors,
        # 'datapoint': datapoint
    }
    return render(request, 'main/sensor.html', context)


def get_sensor_data(request, sensor_num):
    if not request.user.is_authenticated:
        return render(request, 'main/login.html')
    try:
        sensors = Sensor.objects.filter(owner=request.user).get(id=sensor_num)
    except Sensor.DoesNotExist:
        raise Http404("Sensor does not exists")
    ranges = {
        '1': 100,
        '2': 500,
        '3': 1000,
        '4': 10000,
        '5': 999999,
    }
    if request.method == "GET":
        datapoint = DataPoint.objects.filter(sensor=sensors).order_by('-date')[:1000]
        keep = ['date', 'temperature', 'humidity', 'pressure', 'air_direction']
    elif request.method == "POST":
        data_range = ranges.get(request.POST.get('range', '1'), 10)
        datapoint = DataPoint.objects.filter(sensor=sensors).order_by('-date')[:data_range]
        field_names = [field.name for field in datapoint.model._meta.fields]
        keep = ['date'] + [name for name in field_names if name in request.POST]
    else:
        raise Http404("Unknown Request Format")
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': f'attachment; filename="Sensor_{sensor_num}.csv"'},
    )
    writer = csv.writer(response)
    writer.writerow(keep)
    for obj in datapoint:
        writer.writerow([getattr(obj, field) for field in keep])

    return response


def delete_sensor_data(request, sensor_num):
    t = DataPoint.objects.filter(sensor_id=sensor_num).delete()
    try:
        r = f"Sensor {sensor_num} datapoints deleted {t}"
    except:
        r = "Error"
    return HttpResponse(r)

main/templates/main/head.html
{% load static %}
<meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Weather Monitoring System</title>
<link rel="icon" href="{% static 'main/favicon.png' %}" type="image/x-icon"/>
<link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}"/>
<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'main/js/jquery.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'main/css/fontawsome.min.css' %}"/>

<script src="{% static 'main/js/chart.min.js' %}"></script>
<script src="{% static 'main/js/moment.js' %}"></script>
<script src="{% static 'main/js/chartjs-adapter-moment.js' %}"></script>

main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include 'main/head.html' %}
    <!-- <script src="assets/chart.min.js"></script> -->
  </head>
  <body style="background-color: darkslategray">
    {% include 'main/navbar.html' %}
    <main>
      <div class="container mt-3">{% if sensors %}
        <div id="sensor_container" class="row row-cols-1 g-4">
          {% for sensor in sensors %}
          <div class="col">
            <div class="card h-100 text-white bg-dark" id="sensor_{{sensor.id}}">
              <!-- <img src="/static/main/img/placeholder.png" class="card-img-top" alt="..."> -->
              <div class="card-body">
                <div class="d-flex justify-content-between">
                  <a href="{% url 'main:sensor' sensor.id %}" class="card-title" style="font-size: 35px; color: #aca0fd; text-decoration: none;">{{sensor.name}}</a>
                  <a href="{% url 'main:get_sensor_data' sensor.id %}" style="font-size: 35px; color: #aca0fd; text-decoration: none;"><i class="fa-solid fa-download"></i></a>
                </div>
                <p class="card-text">
                  <!-- Temperature: ?? °C<br />
                  Pressure: ?? Pa<br />
                  Humidity: ??%<br />
                  Air Speed: ?? km/h<br /> -->
                  Air Direction: ??<br />
                </p>
                <!-- <ul class="list-group list-group-flush">
                  <li class="list-group-item text-white bg-dark">An item</li>
                  <li class="list-group-item text-white bg-dark">A second item</li>
                  <li class="list-group-item text-white bg-dark">A third item</li>
                </ul> -->
                <!-- <a href="{% url 'main:sensor' sensor.id %}" class="card-link">Details</a> -->
                <div class="row row-cols-1 row-cols-md-2 g-4">
                  <div class="col">
                    <div class="card text-white bg-dark" style="position:relative;">
                      <canvas id="sensor_{{sensor.id}}_temperature_chart" class="card-img-top bg-white"></canvas>
                      <p id="sensor_{{sensor.id}}_temp" style="position: absolute;top: 10px;right: 10px;color: black;">
                        Temperature ?? °C
                      </p>
                    </div>
                  </div>
                  <div class="col">
                    <div class="card text-white bg-dark">
                      <canvas id="sensor_{{sensor.id}}_pressure_chart" class="card-img-top bg-white"></canvas>
                      <p id="sensor_{{sensor.id}}_pres" style="position: absolute;top: 10px;right: 10px;color: black;">Pressure ?? atm</p>
                    </div>
                  </div>
                  <div class="col">
                    <div class="card text-white bg-dark">
                      <!-- <img src="/static/main/img/placeholder.png" class="card-img-top"> -->
                      <canvas id="sensor_{{sensor.id}}_humidity_chart" class="card-img-top bg-white"></canvas>
                      <p id="sensor_{{sensor.id}}_hum" style="position: absolute;top: 10px;right: 10px;color: black;">Humidity ?? %</p>
                    </div>
                  </div>
                  <div class="col">
                    <div class="card text-white bg-dark">
                      <!-- <img src="/static/main/img/placeholder.png" class="card-img-top"> -->
                      <canvas id="sensor_{{sensor.id}}_air_speed_chart" class="card-img-top bg-white"></canvas>
                      <p id="sensor_{{sensor.id}}_air_spd" style="position: absolute;top: 10px;right: 10px;color: black;">Air Speed ?? km/h</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <!--<small class="text-muted" last_updated="{{datapoint.date|date:'U'}}">Last updated 3 mins ago</small>-->
                <small class="text-muted" last_updated="">Last Updated null min ago</small>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>{% else %} NoData Found {% endif %}
      </div>
    </main>
  <script>
    function update_text() {
      var elms = document.getElementsByClassName('card-footer');
      for (i = 0; i < elms.length; i++) {
        var el = elms[i].children[0];
        var d = (Date.now() - new Date(el.getAttribute("last_updated")))/1000;
        var dy = parseInt(d/86400)
        var hr = parseInt(d%86400/3600)
        var mn = parseInt(d%86400%3600/60)
        var ss = parseInt(d%86400%3600%60)
        var txt = "Last Updated "
        if (dy > 0) {
          txt += dy + "day "
          txt += hr + "hr "
          txt += mn + "min "
          txt += ss + "s ago"
        } else if (hr > 0) {
          txt += hr + "hr "
          txt += mn + "min "
          txt += ss + "s ago"
        } else if (mn > 0) {
          txt += mn + "min "
          txt += ss + "s ago"
        } else {
          txt += ss + "s ago"
        }
        el.innerText = txt;
      }
    }
    function update_sensors(){
      // Unused function
      $.getJSON('{% url 'api:get_sensor' %}', function(data){
        $.each(data, function(index, value){
         if (value.datapoint.date === null) return;
          var out = "";
          // out += 'Air Quality: ??<br />'
          out += 'Temperature: ' + value.datapoint.temperature + ' °C<br />';
          out += 'Pressure: ' + value.datapoint.pressure + ' Pa<br />';
          out += 'Humidity: ' + value.datapoint.humidity + '%<br />';
          out += 'Air Speed: ' + value.datapoint.air_speed + ' km/h<br />';
          out += 'Air Direction: ' + value.datapoint.air_direction + '<br />';
          // out += 'Solar Irradiance: ??<br />';
          //$("#sensor_" + value.id + " > .card-body > .row > .col > .card > .card-body > .card-text").html(out);
          $("#sensor_" + value.id + " > .card-body > .card-text").html(out);
          $("#sensor_" + value.id + " > .card-footer > .text-muted").attr("last_updated", value.datapoint.date.toString());
        });
      }).fail(function() {
        console.log( "error" );
      }).always(function(){
        setTimeout(update_sensors, 1000);
      });
    }
    // update_sensors();
    setInterval(update_text, 500);
  </script>
  <script>
    var charts = {};
    sensors = [
    {% for sensor in sensors %}
    {{sensor.id}},
    {% endfor %}
    ];
    $.each(sensors, function( index, sensor) {
      charts[sensor] = {};
      $.each({
        "temperature": "Temperature", 
        "pressure": "Pressure",
        "humidity": "Humidity",
        "air_speed": "Air Speed",
      }, function(key, value) {
        charts[sensor][key] = new Chart($("#sensor_"+sensor+"_"+key+"_chart"), {
          type: "line",
          data: {datasets: [{
            label: value,
            backgroundColor: "rgb(255, 135, 77)",
            borderColor: "rgb(0, 0, 0)",
          }]},
          options: {
            animation: {duration: 0},
            parsing: {
              xAxisKey: 'date',
              yAxisKey: key
            },
            elements: {point:{radius: 0}},
            responsive: true,
            scales: {x: {type: 'time'}, y: {beginAtZero: false}},
            plugins: {
              legend: {
                display: false,
              }
            }
          },
        });
      });
    });
  </script>
  <script>
    var sockets = {};
    $.each(sensors, function( index, sensor) {
      sockets[sensor] = new WebSocket(window.location.protocol.replace('http', 'ws') + '//' + window.location.host + '/ws/plotter/' + sensor);
      
      sockets[sensor].onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data['data'][0]);
        if (data['code'] == 200) {
          if (data['data'].length > 0){
            var out = "";
            // out += 'Temperature: ' + data['data'][0].temperature + ' °C<br />';
            // out += 'Pressure: ' + (data['data'][0].pressure).toFixed(7) + ' Pa<br />';
            // out += 'Humidity: ' + data['data'][0].humidity + '%<br />';
            // out += 'Air Speed: ' + data['data'][0].air_speed + ' km/h<br />';
            out += 'Air Direction: ' + data['data'][0].air_direction + '<br />';
            $("#sensor_" + sensor + " > .card-body > .card-text").html(out);
            $("#sensor_" + sensor + "_temp").html('Temperature: ' + data['data'][0].temperature + ' °C');
            $("#sensor_" + sensor + "_pres").html('Pressure: ' + (data['data'][0].pressure).toFixed(7) + ' atm');
            $("#sensor_" + sensor + "_hum").html('Humidity: ' + data['data'][0].humidity + '%');
            $("#sensor_" + sensor + "_air_spd").html('Air Speed: ' + data['data'][0].air_speed + ' km/h');
            $("#sensor_" + sensor + " > .card-footer > .text-muted").attr("last_updated", data['data'][0].date.toString());
          }
          $.each(charts[sensor], function(key, value){
            value.data.datasets[0].data = data['data'];
            value.update();
          });
        }
      };
      sockets[sensor].onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
      };
      sockets[sensor].onopen = function(e) {
        console.log(sensor);
        sockets[sensor].send(JSON.stringify({
          'sensor_id': sensor,
          'limit': 25,
          'offset': 0
        }));
      };
    });
  </script>
  {% include 'main/footer.html' %}
  </body>
</html>

main/templates/main/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include 'main/head.html' %}
  </head>
  <body style="background-color: darkslategray">
    {% include 'main/navbar.html' %}
    <main>
      <div class="container text-white mx-auto pt-3" style="max-width: 400px;">
        <form action="{% url 'main:login' %}" method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" name="username" class="form-control" id="username"/>
          </div>
          <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" name="password" class="form-control" id="password" />
          </div>
          <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1" />
            <label class="form-check-label" for="exampleCheck1">Remember Me</label>
          </div>
          {% if failed_login %}<div class="alert alert-danger" role="alert">
          Incorrect Username or Password
          </div>{% endif %}
          <button type="submit" class="btn btn-primary">Log In</button>
        </form>
      </div>
    </main>
  </body>
</html>

<!--<form action="{% url 'main:login' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>-->

main/templates/main/navbar.html
{% load static %}
   <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">
          <!-- <img src="icon.png" style="width:32px;"> -->
          <i class="fa-solid fa-cloud-sun"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:about' %}">About</a>
            </li>
          </ul>
          {% if user.is_authenticated %}<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle"  id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="{% static 'main/img/'|add:user.username|add:'.jpg' %}" class="rounded-circle" alt="User" width="28px" />
              </a>
              <div class="dropdown-menu dropdown-menu-sm-end" aria-labelledby="navbarDropdown" style="padding: 0">
                <div class="card text-center">
                  <img src="{% static 'main/img/'|add:user.username|add:'.jpg' %}" class="rounded-circle p-2 card-img-top" alt="User" />
                  <div class="card-body pt-0">
                    <h5 class="card-title">{{ user.first_name }} {{user.last_name}}</h5>
                    <h6 class="card-text mb-3 text-muted">{{ user.email}}</h6>
                    <div class=""><a class="btn btn-danger" href="{% url 'main:logout' %}">Log Out</a></div>
                  </div>
                </div>
              </div>
            </li>
          </ul>{% endif %}
          <!-- <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form> -->
        </div>
      </div>
    </nav>

main/templates/main/sensor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    {% include 'main/head.html' %}
    <style>
      canvas {
        max-height: 50vh;
      }
    </style>
  </head>
  <body style="background-color: darkslategray">
    {% include 'main/navbar.html' %}
    <main>
      <div class="container text-black mt-3">
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Export Data</button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <form action="{% url 'main:get_sensor_data' sensors.id %}" method="post">
                  {% csrf_token %}
                  <!-- <div class="row mb-3">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" id="inputEmail3" />
                    </div>
                  </div>
                  <div class="row mb-3">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                      <input type="password" class="form-control" id="inputPassword3" />
                    </div>
                  </div> -->
                  <div class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">Include</legend>
                    <div class="col-sm-10">
                      <!-- <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck1" />
                        <label class="form-check-label" for="gridCheck1"> Air Quality </label>
                      </div> -->
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck2" name="temperature" />
                        <label class="form-check-label" for="gridCheck2"> Temperature </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck3" name="pressure"/>
                        <label class="form-check-label" for="gridCheck3"> Pressure </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck3" name="humidity"/>
                        <label class="form-check-label" for="gridCheck3"> Humidity </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck3" name="air_speed/>
                        <label class="form-check-label" for="gridCheck3"> Air Speed </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck3" name="air_direction"/>
                        <label class="form-check-label" for="gridCheck3"> Air Direction </label>
                      </div>
                      <!-- <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="gridCheck3" />
                        <label class="form-check-label" for="gridCheck3"> Irradiance </label>
                      </div> -->
                    </div>
                  </div>
                  <div class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">Range</legend>
                    <div class="col-sm-10">
                      <select class="form-select form-select-sm" aria-label="Default select example" name="range">
                        <option selected value="1">Last 100 values</option>
                        <option value="2">Last 500 values</option>
                        <option value="3">Last 1000 values</option>
                        <option value="4">Last 10000 values</option>
                        <option value="5">Last 999999 values</option>
                      </select>
                    </div>
                  </div>
                  <!-- <div class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">Format</legend>
                    <div class="col-sm-10">
                      <select class="form-select form-select-sm" aria-label="Default select example" name="format">
                        <option selected value="1">CSV</option>
                        <option value="2">JSON</option>
                      </select>
                    </div>
                  </div> -->
                  <button type="submit" class="btn btn-primary">Export</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container" id="canvas_container"></div>
      <div class="container" onclick="chart_controls(event);">
        <div class="float" style="bottom: 40px"><i class="fa fa-plus float_item"></i></div>
        <div class="float" style="bottom: 90px"><i class="fa fa-minus float_item"></i></div>
        <div class="float" style="bottom: 140px"><i class="fa fa-angle-left float_item"></i></div>
        <div class="float" style="bottom: 190px"><i class="fa fa-angle-right float_item"></i></div>
      </div>
    </main>
    <style>
      .float {
        position: fixed;
        width: 45px;
        height: 45px;
        right: 40px;
        background-color: #0c9;
        color: #fff;
        border-radius: 25px;
        text-align: center;
        box-shadow: 2px 2px 3px #999;
      }
      .float_item {
        margin-top: 15px;
      }
    </style>
    <script>
      function chart_controls(e){
        if (e.target.nodeName == 'DIV') el = e.target.children[0];
        else el = e.target;
        console.log(el.classList);
        if (el.classList.contains("fa-plus")) data_limit = Math.round(Math.max(data_limit/2, 10), 0);
        if (el.classList.contains("fa-minus")) data_limit = Math.round(Math.min(data_limit*2, 10000), 0);
        if (el.classList.contains("fa-angle-left")) data_offset = Math.round(data_offset + data_limit, 0);
        if (el.classList.contains("fa-angle-right")) data_offset = Math.round(Math.max(data_offset - data_limit, 0), 0);
        send_options();
      }

      var charts = {};
      $.each({
        "temperature": ["Temperature (°C)", { beginAtZero: false, suggestedmax: 35, suggestedMin: 30}], 
        "pressure": ["Pressure (atm)", { beginAtZero: false, suggestedMax: 0.988, suggestedMin: 0.986}],
        "humidity": ["Humidity (%)", { beginAtZero: false, suggestedMax: 70, suggestedMin: 60}],
        "air_speed": ["Air Speed (km/h)", { beginAtZero: false, suggestedMax: 5, suggestedMin: 0}],
      }, function(key, value) {
        h = '<div class="list-group-item border border-3 mt-3"><canvas id="' + key + '_chart"></canvas></div>';
        $("#canvas_container").append(h);
        charts[key] = new Chart($("#" + key + "_chart"), {
          type: "line",
          data: {datasets: [{
            label: value[0],
            backgroundColor: "rgb(255, 135, 77)",
            borderColor: "rgb(0, 0, 0)",
          }]},
          options: {
            animation: {duration: 0},
            parsing: {
              xAxisKey: 'date',
              yAxisKey: key
            },
            elements: {point:{radius: 0}},
            responsive: true,
            scales: {x: {type: 'time'}, y: value[1]},
          },
        });
      });
    </script>
    <script>
      var data_limit = 125;
      var data_offset = 0;
      const chatSocket = new WebSocket(window.location.protocol.replace('http', 'ws') + '//' + window.location.host + '/ws/plotter/{{sensors.id}}');
      chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data);
        if (data['code'] == 200) {
          $.each(charts, function(key, value){
            value.data.datasets[0].data = data['data'];
            value.update();
          });
        }
      };
      chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
      };
      chatSocket.onopen = function(e) {
        send_options();
      };
      function send_options(){
        chatSocket.send(JSON.stringify({
          'sensor_id': '{{sensors.id}}',
          'limit': data_limit,
          'offset': data_offset
        }));
      }
    </script>
  {% include 'main/footer.html' %}
  </body>
</html>